apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink01
spec:
  image: flink01:1
  flinkVersion: v1_15
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1