apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: example-app
  podMetricsEndpoints:
    - port: web